vqgan:
  config: configs/Encoders/config_vqgan.json
  checkpoint: /projects/0/prjs0951/Varun/Checkpoints/vqgan_knmi_7M_1024_ckpt-177500.pt

blockGPT_models:
  - name: blockGPT_seed1
    config: configs/GPT/config_blockGPT_KNMI5.json
    checkpoint: /projects/0/prjs0951/Varun/FinalCheckpoints/blockGPT_KNMI5_seed1.safetensors
    vqgan_type: vqgan

  - name: blockGPT_seed2
    config: configs/GPT/config_blockGPT_KNMI5.json
    checkpoint: /projects/0/prjs0951/Varun/FinalCheckpoints/blockGPT_KNMI5_seed2.safetensors
    vqgan_type: vqgan

  - name: blockGPT_seed3
    config: configs/GPT/config_blockGPT_KNMI5.json
    checkpoint: /projects/0/prjs0951/Varun/FinalCheckpoints/blockGPT_KNMI5_seed3.safetensors
    vqgan_type: vqgan

  #Nowcasting
  - name: nowcastingGPT_seed1
    config: configs/GPT/config_nowcasting_KNMI5.json
    checkpoint: /projects/0/prjs0951/Varun/FinalCheckpoints/nowcastingGPT_KNMI5_seed1.safetensors
    vqgan_type: vqgan

  - name: nowcastingGPT_seed2
    config: configs/GPT/config_nowcasting_KNMI5.json
    checkpoint: /projects/0/prjs0951/Varun/FinalCheckpoints/nowcastingGPT_KNMI5_seed2.safetensors
    vqgan_type: vqgan
  - name: nowcastingGPT_seed3
    config: configs/GPT/config_nowcasting_KNMI5.json
    checkpoint: /projects/0/prjs0951/Varun/FinalCheckpoints/nowcastingGPT_KNMI5_seed3.safetensors
    vqgan_type: vqgan

diffcast_models:
  - name: diffcast_phydnet_seed1
    checkpoint: /projects/0/prjs0951/Varun/FinalCheckpoints/diffcast_phydnet_KNMI5_seed1.pt
    use_BlockGPT: false

  - name: diffcast_phydnet_seed2
    checkpoint: /projects/0/prjs0951/Varun/FinalCheckpoints/diffcast_phydnet_KNMI5_seed2.pt
    use_BlockGPT: false

  - name: diffcast_phydnet_seed3
    checkpoint: /projects/0/prjs0951/Varun/FinalCheckpoints/diffcast_phydnet_KNMI5_seed3.pt
    use_BlockGPT: false
kwargs:
   in_shape: [1, 128, 128]

#python evaluate.py --debug --dataset_name 'knmi_5mins' --segment_length 25 --context_length 5 --eval_FinalCheckpoints "evaluate_config_KNMI5.yaml" --time_resolution 5