vqgan:
  config: configs/Encoders/config_vqgan.json
  checkpoint: /projects/0/prjs0951/Varun/Checkpoints/vqgan_sevir_7M_1024ckpt-267880.pt

blockGPT_models:
  - name: blockGPT_seed1
    config: configs/GPT/config_blockGPT_SEVIR30.json 
    checkpoint:  /projects/0/prjs0951/Varun/Checkpoints/FinalCheckpoints/blockGPT_SEVIR30_seed1.safetensors
    vqgan_type: vqgan
  - name: blockGPT_seed2
    config: configs/GPT/config_blockGPT_SEVIR30.json 
    checkpoint:  /projects/0/prjs0951/Varun/Checkpoints/FinalCheckpoints/blockGPT_SEVIR30_seed2.safetensors
    vqgan_type: vqgan
  - name: blockGPT_seed3
    config: configs/GPT/config_blockGPT_SEVIR30.json 
    checkpoint:  /projects/0/prjs0951/Varun/Checkpoints/FinalCheckpoints/blockGPT_SEVIR30_seed3.safetensors
    vqgan_type: vqgan

    #Nowcasting
  - name: nowcastingGPT_seed1
    config: configs/GPT/config_nowcasting_SEVIR30.json
    checkpoint: /projects/0/prjs0951/Varun/Checkpoints/FinalCheckpoints/nowcastingGPT_SEVIR30_seed1.safetensors
    vqgan_type: vqgan
  - name: nowcastingGPT_seed2
    config: configs/GPT/config_nowcasting_SEVIR30.json
    checkpoint: /projects/0/prjs0951/Varun/Checkpoints/FinalCheckpoints/nowcastingGPT_SEVIR30_seed2.safetensors
    vqgan_type: vqgan
  - name: nowcastingGPT_seed3
    config: configs/GPT/config_nowcasting_SEVIR30.json
    checkpoint: /projects/0/prjs0951/Varun/Checkpoints/FinalCheckpoints/nowcastingGPT_SEVIR30_seed3.safetensors
    vqgan_type: vqgan


diffcast_models:
  - name: diffcast_phydnet_seed1
    checkpoint: /projects/0/prjs0951/Varun/Checkpoints/FinalCheckpoints/diffcast_phydnet_SEVIR30_seed1.pt
    use_BlockGPT: false
  - name: diffcast_phydnet_seed2
    checkpoint: /projects/0/prjs0951/Varun/Checkpoints/FinalCheckpoints/diffcast_phydnet_SEVIR30_seed2.pt
    use_BlockGPT: false
  - name: diffcast_phydnet_seed3
    checkpoint: /projects/0/prjs0951/Varun/Checkpoints/FinalCheckpoints/diffcast_phydnet_SEVIR30_seed3.pt
    use_BlockGPT: false

  - name: diffcast_blockgpt_seed1
    checkpoint: /projects/0/prjs0951/Varun/Checkpoints/FinalCheckpoints/diffcast_blockgpt_SEVIR30_seed1.pt
    config_path: configs/config_blockGPTBackbone_SEVIR30.json
    use_BlockGPT: true
  - name: diffcast_blockgpt_seed2
    checkpoint: /projects/0/prjs0951/Varun/Checkpoints/FinalCheckpoints/diffcast_blockgpt_SEVIR30_seed2.pt
    config_path: configs/config_blockGPTBackbone_SEVIR30.json
    use_BlockGPT: true
  - name: diffcast_blockgpt_seed2
    checkpoint: /projects/0/prjs0951/Varun/Checkpoints/FinalCheckpoints/diffcast_blockgpt_SEVIR30_seed3.pt
    config_path: configs/config_blockGPTBackbone_SEVIR30.json
    use_BlockGPT: true

kwargs:
   in_shape: [1, 128, 128]
#python evaluate.py --debug --dataset_name 'sevir' --segment_length 9 --context_length 3 --eval_checkpoints "evaluate_config_SEVIR30.yaml" --time_resolution 30 --seq_len_sevir 49